version: '3'
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=mysecretpassword1234"

  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ".:/app"
    environment:
      - "DATABASE_HOST=db"
      - "DATABASE_PORT=5432"
      - "DATABASE_USER=postgres"
      - "DATABASE_PASSWORD=mysecretpassword1234"
    depends_on:
      - db
    tty: true
    stdin_open: true
